# MySQL.  Versions 5.0+ are recommended.

default: &default
  adapter: mysql2
  encoding: utf8
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>

development:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>

test:
  adapter: mysql2
  encoding: utf8
  username: root
  password: 
  # Jeongbin's Ubuntu 14.04
  pool: 5
  socket: /var/run/mysqld/mysqld.sock
  database: new_MenuMap_test

production:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>
